
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          - Automated release from tag ${{ github.ref }}
          
          ## Installation
          ```bash
          git clone https://github.com/yoel2019/eic-inspection-app.git
          cd eic-inspection-app
          git checkout ${{ github.ref }}
          npm install
          ```
        draft: false
        prerelease: false
